#!/bin/bash
echo "=== Getting Started with Cryptographic Polynomial Analyzer ==="
echo ""
echo "1. Clone the repository:"
echo "   git clone https://github.com/hirajiv-lab/crypto-polynomial-analyzer.git"
echo "   cd crypto-polynomial-analyzer"
echo ""
echo "2. Install SageMath:"
echo "   # Using conda (recommended):"
echo "   conda create -n sage sage python=3.11"
echo "   conda activate sage"
echo ""
echo "   # Or using system package:"
echo "   sudo apt install sagemath"
echo ""
echo "3. Run the analyzer:"
echo "   sage slk2_analyzer_truly_final.sage"
echo ""
echo "4. Test a custom polynomial:"
echo "   sage quick_crypto_check.sage"
echo ""
echo "5. Fork and contribute:"
echo "   - Click 'Fork' on GitHub"
echo "   - Create a branch for your changes"
echo "   - Submit a pull request"
echo ""
echo "For questions or issues:"
echo "   https://github.com/hirajiv-lab/crypto-polynomial-analyzer/issues"
